package admgql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"sajudating_api/api/admgql/admgql_generated"
	"sajudating_api/api/admgql/model"
	"sajudating_api/api/utils"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, otp string) (*model.SimpleResult, error) {
	return getAdminUserService().Login(ctx, email, password, otp)
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*model.SimpleResult, error) {
	return getAdminUserService().Logout(ctx)
}

// CreateAdminUser is the resolver for the createAdminUser field.
func (r *mutationResolver) CreateAdminUser(ctx context.Context, email string, password string) (*model.SimpleResult, error) {
	return getAdminUserService().CreateAdminUser(ctx, email, password)
}

// SetAdminUserActive is the resolver for the setAdminUserActive field.
func (r *mutationResolver) SetAdminUserActive(ctx context.Context, uid string, active bool) (*model.SimpleResult, error) {
	return getAdminUserService().SetAdminUserActive(ctx, uid, active)
}

// UpdateAdminUser is the resolver for the updateAdminUser field.
func (r *mutationResolver) UpdateAdminUser(ctx context.Context, uid string, email string, password string) (*model.SimpleResult, error) {
	return getAdminUserService().UpdateAdminUser(ctx, uid, email, password)
}

// CreateSajuProfile is the resolver for the createSajuProfile field.
func (r *mutationResolver) CreateSajuProfile(ctx context.Context, input model.SajuProfileCreateInput) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().CreateSajuProfileGql(ctx, input)
}

// DeleteSajuProfile is the resolver for the deleteSajuProfile field.
func (r *mutationResolver) DeleteSajuProfile(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().DeleteSajuProfileGql(ctx, uid)
}

// CreatePhyIdealPartner is the resolver for the createPhyIdealPartner field.
func (r *mutationResolver) CreatePhyIdealPartner(ctx context.Context, input model.PhyIdealPartnerCreateInput) (*model.SimpleResult, error) {
	return getAdminPhyPartnerService().CreatePhyPartnerGql(ctx, input)
}

// DeletePhyIdealPartner is the resolver for the deletePhyIdealPartner field.
func (r *mutationResolver) DeletePhyIdealPartner(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminPhyPartnerService().DeletePhyPartnerGql(ctx, uid)
}

// PutAiMeta is the resolver for the putAiMeta field.
func (r *mutationResolver) PutAiMeta(ctx context.Context, input model.AiMetaInput) (*model.SimpleResult, error) {
	return getAdminAiMetaService().PutAiMeta(ctx, input)
}

// SetAiMetaInUse is the resolver for the setAiMetaInUse field.
func (r *mutationResolver) SetAiMetaInUse(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiMetaService().SetAiMetaInUse(ctx, uid)
}

// DelAiMeta is the resolver for the delAiMeta field.
func (r *mutationResolver) DelAiMeta(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiMetaService().DelAiMeta(ctx, uid)
}

// SetAiMetaDefault is the resolver for the setAiMetaDefault field.
func (r *mutationResolver) SetAiMetaDefault(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiMetaService().SetAiMetaDefault(ctx, uid)
}

// RunAiExecution is the resolver for the runAiExecution field.
func (r *mutationResolver) RunAiExecution(ctx context.Context, input model.AiExcutionInput) (*model.SimpleResult, error) {
	return getAdminAiExecutionService().RunAiExecution(ctx, input, utils.StrPtr("admin"), nil)
}

// CreateItemnCard is the resolver for the createItemnCard field.
func (r *mutationResolver) CreateItemnCard(ctx context.Context, input model.ItemNCardInput) (*model.SimpleResult, error) {
	return getAdminItemNCardService().CreateItemnCard(ctx, input)
}

// UpdateItemnCard is the resolver for the updateItemnCard field.
func (r *mutationResolver) UpdateItemnCard(ctx context.Context, uid string, input model.ItemNCardInput) (*model.SimpleResult, error) {
	return getAdminItemNCardService().UpdateItemnCard(ctx, uid, input)
}

// DeleteItemnCard is the resolver for the deleteItemnCard field.
func (r *mutationResolver) DeleteItemnCard(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminItemNCardService().DeleteItemnCard(ctx, uid)
}

// RunSajuGeneration is the resolver for the runSajuGeneration field.
func (r *mutationResolver) RunSajuGeneration(ctx context.Context, input model.SajuGenerationRequest) (*model.SajuGenerationResponse, error) {
	return getAdminExtractService().RunSajuGenerationGql(ctx, input)
}

// RunChemiGeneration is the resolver for the runChemiGeneration field.
func (r *mutationResolver) RunChemiGeneration(ctx context.Context, input model.ChemiGenerationRequest) (*model.ChemiGenerationResponse, error) {
	return getAdminExtractService().RunChemiGenerationGql(ctx, input)
}

// SendLLMRequest is the resolver for the sendLLMRequest field. Delegates to AdminExtractService (SajuAssemble 공통 LLM 요청).
func (r *mutationResolver) SendLLMRequest(ctx context.Context, input model.SendLLMRequestInput) (*model.SimpleResult, error) {
	return getAdminExtractService().SendLLMRequestGql(ctx, input)
}

// Image is the resolver for the image field.
func (r *phyIdealPartnerResolver) Image(ctx context.Context, obj *model.PhyIdealPartner) (string, error) {
	return getAdminPhyPartnerService().GetPhyPartnerImage(ctx, obj.UID)
}

// AdminUsers is the resolver for the adminUsers field.
func (r *queryResolver) AdminUsers(ctx context.Context) (*model.SimpleResult, error) {
	return getAdminUserService().GetAdminUsers(ctx)
}

// SajuProfiles is the resolver for the sajuProfiles field.
func (r *queryResolver) SajuProfiles(ctx context.Context, input model.SajuProfileSearchInput) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().GetSajuProfiles(ctx, input)
}

// SajuProfile is the resolver for the sajuProfile field.
func (r *queryResolver) SajuProfile(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().GetSajuProfile(ctx, uid)
}

// SajuProfileSimilarPartners is the resolver for the sajuProfileSimilarPartners field.
func (r *queryResolver) SajuProfileSimilarPartners(ctx context.Context, uid string, limit int, offset int) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().GetSajuProfileSimilarPartners(ctx, uid, limit, offset)
}

// SajuProfileLogs is the resolver for the sajuProfileLogs field.
func (r *queryResolver) SajuProfileLogs(ctx context.Context, input model.SajuProfileLogSearchInput) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().GetSajuProfileLogs(ctx, input)
}

// PhyIdealPartners is the resolver for the phyIdealPartners field.
func (r *queryResolver) PhyIdealPartners(ctx context.Context, input model.PhyIdealPartnerSearchInput) (*model.SimpleResult, error) {
	return getAdminPhyPartnerService().GetPhyPartners(ctx, input)
}

// PhyIdealPartner is the resolver for the phyIdealPartner field.
func (r *queryResolver) PhyIdealPartner(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminPhyPartnerService().GetPhyPartner(ctx, uid)
}

// AiMetas is the resolver for the aiMetas field.
func (r *queryResolver) AiMetas(ctx context.Context, input model.AiMetaSearchInput) (*model.SimpleResult, error) {
	return getAdminAiMetaService().GetAiMetas(ctx, input)
}

// AiMeta is the resolver for the aiMeta field.
func (r *queryResolver) AiMeta(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiMetaService().GetAiMeta(ctx, uid)
}

// AiMetaTypes is the resolver for the aiMetaTypes field.
func (r *queryResolver) AiMetaTypes(ctx context.Context) (*model.SimpleResult, error) {
	return getAdminAiMetaService().GetAiMetaTypes(ctx)
}

// AiMetaKVs is the resolver for the aiMetaKVs field.
func (r *queryResolver) AiMetaKVs(ctx context.Context, input model.AiMetaKVsInput) (*model.SimpleResult, error) {
	return getAdminAiMetaService().GetAiMetaKVs(ctx, input)
}

// AiExecutions is the resolver for the aiExecutions field.
func (r *queryResolver) AiExecutions(ctx context.Context, input model.AiExecutionSearchInput) (*model.SimpleResult, error) {
	return getAdminAiExecutionService().GetAiExecutions(ctx, input)
}

// AiExecution is the resolver for the aiExecution field.
func (r *queryResolver) AiExecution(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiExecutionService().GetAiExecution(ctx, uid)
}

// Palja is the resolver for the palja field.
func (r *queryResolver) Palja(ctx context.Context, birthdate string, timezone string) (*model.SimpleResult, error) {
	return getAdminToolService().GetPaljaGql(ctx, birthdate, timezone)
}

// ItemnCards is the resolver for the itemnCards field.
func (r *queryResolver) ItemnCards(ctx context.Context, input model.ItemNCardSearchInput) (*model.SimpleResult, error) {
	return getAdminItemNCardService().GetItemnCards(ctx, input)
}

// ItemnCard is the resolver for the itemnCard field.
func (r *queryResolver) ItemnCard(ctx context.Context, uid *string) (*model.SimpleResult, error) {
	return getAdminItemNCardService().GetItemnCard(ctx, uid)
}

// ItemnCardByCardID is the resolver for the itemnCardByCardId field.
func (r *queryResolver) ItemnCardByCardID(ctx context.Context, cardID string, scope *string) (*model.SimpleResult, error) {
	return getAdminItemNCardService().GetItemnCardByCardID(ctx, cardID, scope)
}

// SajuChart is the resolver for the sajuChart field. Delegates to AdminExtractService (단일 명식 차트: pillars + items + tokens).
func (r *queryResolver) SajuChart(ctx context.Context, input model.SajuChartInput) (*model.SimpleResult, error) {
	return getAdminExtractService().SajuChartGql(ctx, input)
}

// ItemnCardsByTokens is the resolver for the itemnCardsByTokens field. Delegates to AdminExtractService (사주 전용 토큰→카드 선별).
func (r *queryResolver) ItemnCardsByTokens(ctx context.Context, input model.ItemnCardsByTokensInput) (*model.SimpleResult, error) {
	return getAdminExtractService().ItemnCardsByTokensGql(ctx, input)
}

// ExtractSaju is the resolver for the extract_saju field.
func (r *queryResolver) ExtractSaju(ctx context.Context, input model.ExtractSajuInput) (*model.SimpleResult, error) {
	return getExtractSajuPairService().ExtractSajuGql(ctx, input)
}

// SajuPairChart is the resolver for the sajuPairChart field. Delegates to AdminExtractService (궁합 쌍 차트: A/B + pTokens).
func (r *queryResolver) SajuPairChart(ctx context.Context, input model.SajuPairChartInput) (*model.SimpleResult, error) {
	return getAdminExtractService().SajuPairChartGql(ctx, input)
}

// PairCardsByTokens is the resolver for the pairCardsByTokens field. Delegates to AdminExtractService (궁합 전용 토큰→카드 선별).
func (r *queryResolver) PairCardsByTokens(ctx context.Context, input model.PairCardsByTokensInput) (*model.SimpleResult, error) {
	return getAdminExtractService().PairCardsByTokensGql(ctx, input)
}

// ExtractPair is the resolver for the extract_pair field.
func (r *queryResolver) ExtractPair(ctx context.Context, input model.ExtractPairInput) (*model.SimpleResult, error) {
	return getExtractSajuPairService().ExtractPairGql(ctx, input)
}

// LocalLogs is the resolver for the localLogs field.
func (r *queryResolver) LocalLogs(ctx context.Context, input model.LocalLogSearchInput) (*model.SimpleResult, error) {
	return getLocalLogService().GetLocalLogs(ctx, input)
}

// SystemStats is the resolver for the systemStats field.
func (r *queryResolver) SystemStats(ctx context.Context) (*model.SimpleResult, error) {
	return getLocalLogService().GetSystemStats(ctx)
}

// Image is the resolver for the image field.
func (r *sajuProfileResolver) Image(ctx context.Context, obj *model.SajuProfile) (string, error) {
	return getAdminSajuProfileService().GetSajuProfileImage(ctx, obj.UID)
}

// Mutation returns admgql_generated.MutationResolver implementation.
func (r *Resolver) Mutation() admgql_generated.MutationResolver { return &mutationResolver{r} }

// PhyIdealPartner returns admgql_generated.PhyIdealPartnerResolver implementation.
func (r *Resolver) PhyIdealPartner() admgql_generated.PhyIdealPartnerResolver {
	return &phyIdealPartnerResolver{r}
}

// Query returns admgql_generated.QueryResolver implementation.
func (r *Resolver) Query() admgql_generated.QueryResolver { return &queryResolver{r} }

// SajuProfile returns admgql_generated.SajuProfileResolver implementation.
func (r *Resolver) SajuProfile() admgql_generated.SajuProfileResolver { return &sajuProfileResolver{r} }

type mutationResolver struct{ *Resolver }
type phyIdealPartnerResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sajuProfileResolver struct{ *Resolver }
