package admgql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"sajudating_api/api/admgql/admgql_generated"
	"sajudating_api/api/admgql/model"
)

// CreateSajuProfile is the resolver for the createSajuProfile field.
func (r *mutationResolver) CreateSajuProfile(ctx context.Context, input model.SajuProfileCreateInput) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().CreateSajuProfileGql(ctx, input)
}

// DeleteSajuProfile is the resolver for the deleteSajuProfile field.
func (r *mutationResolver) DeleteSajuProfile(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().DeleteSajuProfileGql(ctx, uid)
}

// CreatePhyIdealPartner is the resolver for the createPhyIdealPartner field.
func (r *mutationResolver) CreatePhyIdealPartner(ctx context.Context, input model.PhyIdealPartnerCreateInput) (*model.SimpleResult, error) {
	return getAdminPhyPartnerService().CreatePhyPartnerGql(ctx, input)
}

// DeletePhyIdealPartner is the resolver for the deletePhyIdealPartner field.
func (r *mutationResolver) DeletePhyIdealPartner(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminPhyPartnerService().DeletePhyPartnerGql(ctx, uid)
}

// PutAiMeta is the resolver for the putAiMeta field.
func (r *mutationResolver) PutAiMeta(ctx context.Context, input model.AiMetaInput) (*model.SimpleResult, error) {
	return getAdminAiMetaService().PutAiMeta(ctx, input)
}

// DelAiMeta is the resolver for the delAiMeta field.
func (r *mutationResolver) DelAiMeta(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiMetaService().DelAiMeta(ctx, uid)
}

// SetAiMetaDefault is the resolver for the setAiMetaDefault field.
func (r *mutationResolver) SetAiMetaDefault(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiMetaService().SetAiMetaDefault(ctx, uid)
}

// RunAiExecution is the resolver for the runAiExecution field.
func (r *mutationResolver) RunAiExecution(ctx context.Context, input model.AiExcutionInput) (*model.SimpleResult, error) {
	return getAdminAiExecutionService().RunAiExecution(ctx, input)
}

// Image is the resolver for the image field.
func (r *phyIdealPartnerResolver) Image(ctx context.Context, obj *model.PhyIdealPartner) (string, error) {
	return getAdminPhyPartnerService().GetPhyPartnerImage(ctx, obj.UID)
}

// SajuProfiles is the resolver for the sajuProfiles field.
func (r *queryResolver) SajuProfiles(ctx context.Context, input model.SajuProfileSearchInput) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().GetSajuProfiles(ctx, input)
}

// SajuProfile is the resolver for the sajuProfile field.
func (r *queryResolver) SajuProfile(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().GetSajuProfile(ctx, uid)
}

// SajuProfileSimilarPartners is the resolver for the sajuProfileSimilarPartners field.
func (r *queryResolver) SajuProfileSimilarPartners(ctx context.Context, uid string, limit int, offset int) (*model.SimpleResult, error) {
	return getAdminSajuProfileService().GetSajuProfileSimilarPartners(ctx, uid, limit, offset)
}

// PhyIdealPartners is the resolver for the phyIdealPartners field.
func (r *queryResolver) PhyIdealPartners(ctx context.Context, input model.PhyIdealPartnerSearchInput) (*model.SimpleResult, error) {
	return getAdminPhyPartnerService().GetPhyPartners(ctx, input)
}

// PhyIdealPartner is the resolver for the phyIdealPartner field.
func (r *queryResolver) PhyIdealPartner(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminPhyPartnerService().GetPhyPartner(ctx, uid)
}

// AiMetas is the resolver for the aiMetas field.
func (r *queryResolver) AiMetas(ctx context.Context, input model.AiMetaSearchInput) (*model.SimpleResult, error) {
	return getAdminAiMetaService().GetAiMetas(ctx, input)
}

// AiMeta is the resolver for the aiMeta field.
func (r *queryResolver) AiMeta(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiMetaService().GetAiMeta(ctx, uid)
}

// AiExecutions is the resolver for the aiExecutions field.
func (r *queryResolver) AiExecutions(ctx context.Context, input model.AiExecutionSearchInput) (*model.SimpleResult, error) {
	return getAdminAiExecutionService().GetAiExecutions(ctx, input)
}

// AiExecution is the resolver for the aiExecution field.
func (r *queryResolver) AiExecution(ctx context.Context, uid string) (*model.SimpleResult, error) {
	return getAdminAiExecutionService().GetAiExecution(ctx, uid)
}

// Palja is the resolver for the palja field.
func (r *queryResolver) Palja(ctx context.Context, birthdate string, timezone string) (*model.SimpleResult, error) {
	return getAdminToolService().GetPaljaGql(ctx, birthdate, timezone)
}

// Image is the resolver for the image field.
func (r *sajuProfileResolver) Image(ctx context.Context, obj *model.SajuProfile) (string, error) {
	return getAdminSajuProfileService().GetSajuProfileImage(ctx, obj.UID)
}

// Mutation returns admgql_generated.MutationResolver implementation.
func (r *Resolver) Mutation() admgql_generated.MutationResolver { return &mutationResolver{r} }

// PhyIdealPartner returns admgql_generated.PhyIdealPartnerResolver implementation.
func (r *Resolver) PhyIdealPartner() admgql_generated.PhyIdealPartnerResolver {
	return &phyIdealPartnerResolver{r}
}

// Query returns admgql_generated.QueryResolver implementation.
func (r *Resolver) Query() admgql_generated.QueryResolver { return &queryResolver{r} }

// SajuProfile returns admgql_generated.SajuProfileResolver implementation.
func (r *Resolver) SajuProfile() admgql_generated.SajuProfileResolver { return &sajuProfileResolver{r} }

type mutationResolver struct{ *Resolver }
type phyIdealPartnerResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sajuProfileResolver struct{ *Resolver }
