// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package admgql_generated

import (
	"bytes"
	"context"
	"errors"
	"sajudating_api/api/admgql/model"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Mutation() MutationResolver
	PhyIdealPartner() PhyIdealPartnerResolver
	Query() QueryResolver
	SajuProfile() SajuProfileResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	AiExecution struct {
		CreatedAt         func(childComplexity int) int
		ElapsedTime       func(childComplexity int) int
		ErrorMessage      func(childComplexity int) int
		ID                func(childComplexity int) int
		InputImageBase64  func(childComplexity int) int
		InputTokens       func(childComplexity int) int
		Inputkvs          func(childComplexity int) int
		MaxTokens         func(childComplexity int) int
		MetaType          func(childComplexity int) int
		MetaUID           func(childComplexity int) int
		Model             func(childComplexity int) int
		OutputImageBase64 func(childComplexity int) int
		OutputText        func(childComplexity int) int
		OutputTokens      func(childComplexity int) int
		Outputkvs         func(childComplexity int) int
		Prompt            func(childComplexity int) int
		RunBy             func(childComplexity int) int
		RunSajuProfileUID func(childComplexity int) int
		Size              func(childComplexity int) int
		Status            func(childComplexity int) int
		Temperature       func(childComplexity int) int
		TotalTokens       func(childComplexity int) int
		UID               func(childComplexity int) int
		UpdatedAt         func(childComplexity int) int
		ValuedPrompt      func(childComplexity int) int
	}

	AiMeta struct {
		CreatedAt   func(childComplexity int) int
		Desc        func(childComplexity int) int
		ID          func(childComplexity int) int
		InUse       func(childComplexity int) int
		MaxTokens   func(childComplexity int) int
		MetaType    func(childComplexity int) int
		Model       func(childComplexity int) int
		Name        func(childComplexity int) int
		Prompt      func(childComplexity int) int
		Size        func(childComplexity int) int
		Temperature func(childComplexity int) int
		UID         func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	AiMetaType struct {
		HasInputImage  func(childComplexity int) int
		HasOutputImage func(childComplexity int) int
		ID             func(childComplexity int) int
		InputFields    func(childComplexity int) int
		OutputFields   func(childComplexity int) int
		Type           func(childComplexity int) int
	}

	KV struct {
		K func(childComplexity int) int
		V func(childComplexity int) int
	}

	Mutation struct {
		CreatePhyIdealPartner func(childComplexity int, input model.PhyIdealPartnerCreateInput) int
		CreateSajuProfile     func(childComplexity int, input model.SajuProfileCreateInput) int
		DelAiMeta             func(childComplexity int, uid string) int
		DeletePhyIdealPartner func(childComplexity int, uid string) int
		DeleteSajuProfile     func(childComplexity int, uid string) int
		PutAiMeta             func(childComplexity int, input model.AiMetaInput) int
		RunAiExecution        func(childComplexity int, input model.AiExcutionInput) int
		SetAiMetaDefault      func(childComplexity int, uid string) int
		SetAiMetaInUse        func(childComplexity int, uid string) int
	}

	PhyIdealPartner struct {
		Age              func(childComplexity int) int
		CreatedAt        func(childComplexity int) int
		EmbeddingModel   func(childComplexity int) int
		EmbeddingText    func(childComplexity int) int
		FeatureEyes      func(childComplexity int) int
		FeatureFaceShape func(childComplexity int) int
		FeatureMouth     func(childComplexity int) int
		FeatureNose      func(childComplexity int) int
		HasImage         func(childComplexity int) int
		ID               func(childComplexity int) int
		Image            func(childComplexity int) int
		PersonalityMatch func(childComplexity int) int
		Sex              func(childComplexity int) int
		SimilarityScore  func(childComplexity int) int
		Summary          func(childComplexity int) int
		UID              func(childComplexity int) int
		UpdatedAt        func(childComplexity int) int
	}

	Query struct {
		AiExecution                func(childComplexity int, uid string) int
		AiExecutions               func(childComplexity int, input model.AiExecutionSearchInput) int
		AiMeta                     func(childComplexity int, uid string) int
		AiMetaKVs                  func(childComplexity int, input model.AiMetaKVsInput) int
		AiMetaTypes                func(childComplexity int) int
		AiMetas                    func(childComplexity int, input model.AiMetaSearchInput) int
		Palja                      func(childComplexity int, birthdate string, timezone string) int
		PhyIdealPartner            func(childComplexity int, uid string) int
		PhyIdealPartners           func(childComplexity int, input model.PhyIdealPartnerSearchInput) int
		SajuProfile                func(childComplexity int, uid string) int
		SajuProfileLogs            func(childComplexity int, input model.SajuProfileLogSearchInput) int
		SajuProfileSimilarPartners func(childComplexity int, uid string, limit int, offset int) int
		SajuProfiles               func(childComplexity int, input model.SajuProfileSearchInput) int
	}

	SajuProfile struct {
		Birthdate               func(childComplexity int) int
		CreatedAt               func(childComplexity int) int
		Email                   func(childComplexity int) int
		ID                      func(childComplexity int) int
		Image                   func(childComplexity int) int
		ImageMimeType           func(childComplexity int) int
		MyFeatureEyes           func(childComplexity int) int
		MyFeatureFaceShape      func(childComplexity int) int
		MyFeatureMouth          func(childComplexity int) int
		MyFeatureNose           func(childComplexity int) int
		MyFeatureNotes          func(childComplexity int) int
		Nickname                func(childComplexity int) int
		Palja                   func(childComplexity int) int
		PartnerAge              func(childComplexity int) int
		PartnerEmbeddingText    func(childComplexity int) int
		PartnerFeatureEyes      func(childComplexity int) int
		PartnerFeatureFaceShape func(childComplexity int) int
		PartnerFeatureMouth     func(childComplexity int) int
		PartnerFeatureNose      func(childComplexity int) int
		PartnerMatchTips        func(childComplexity int) int
		PartnerPersonalityMatch func(childComplexity int) int
		PartnerSex              func(childComplexity int) int
		PartnerSummary          func(childComplexity int) int
		PhyContent              func(childComplexity int) int
		PhyPartnerSimilarity    func(childComplexity int) int
		PhyPartnerUID           func(childComplexity int) int
		PhySummary              func(childComplexity int) int
		SajuContent             func(childComplexity int) int
		SajuSummary             func(childComplexity int) int
		Sex                     func(childComplexity int) int
		UID                     func(childComplexity int) int
		UpdatedAt               func(childComplexity int) int
	}

	SajuProfileLog struct {
		CreatedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		SajuUID   func(childComplexity int) int
		Status    func(childComplexity int) int
		Text      func(childComplexity int) int
		UID       func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
	}

	SimpleResult struct {
		Base64Value func(childComplexity int) int
		Err         func(childComplexity int) int
		Kvs         func(childComplexity int) int
		Limit       func(childComplexity int) int
		Msg         func(childComplexity int) int
		Node        func(childComplexity int) int
		Nodes       func(childComplexity int) int
		Offset      func(childComplexity int) int
		Ok          func(childComplexity int) int
		Total       func(childComplexity int) int
		UID         func(childComplexity int) int
		Value       func(childComplexity int) int
	}
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "AiExecution.createdAt":
		if e.complexity.AiExecution.CreatedAt == nil {
			break
		}

		return e.complexity.AiExecution.CreatedAt(childComplexity), true

	case "AiExecution.elapsedTime":
		if e.complexity.AiExecution.ElapsedTime == nil {
			break
		}

		return e.complexity.AiExecution.ElapsedTime(childComplexity), true

	case "AiExecution.errorMessage":
		if e.complexity.AiExecution.ErrorMessage == nil {
			break
		}

		return e.complexity.AiExecution.ErrorMessage(childComplexity), true

	case "AiExecution.id":
		if e.complexity.AiExecution.ID == nil {
			break
		}

		return e.complexity.AiExecution.ID(childComplexity), true

	case "AiExecution.inputImageBase64":
		if e.complexity.AiExecution.InputImageBase64 == nil {
			break
		}

		return e.complexity.AiExecution.InputImageBase64(childComplexity), true

	case "AiExecution.inputTokens":
		if e.complexity.AiExecution.InputTokens == nil {
			break
		}

		return e.complexity.AiExecution.InputTokens(childComplexity), true

	case "AiExecution.inputkvs":
		if e.complexity.AiExecution.Inputkvs == nil {
			break
		}

		return e.complexity.AiExecution.Inputkvs(childComplexity), true

	case "AiExecution.maxTokens":
		if e.complexity.AiExecution.MaxTokens == nil {
			break
		}

		return e.complexity.AiExecution.MaxTokens(childComplexity), true

	case "AiExecution.metaType":
		if e.complexity.AiExecution.MetaType == nil {
			break
		}

		return e.complexity.AiExecution.MetaType(childComplexity), true

	case "AiExecution.metaUid":
		if e.complexity.AiExecution.MetaUID == nil {
			break
		}

		return e.complexity.AiExecution.MetaUID(childComplexity), true

	case "AiExecution.model":
		if e.complexity.AiExecution.Model == nil {
			break
		}

		return e.complexity.AiExecution.Model(childComplexity), true

	case "AiExecution.outputImageBase64":
		if e.complexity.AiExecution.OutputImageBase64 == nil {
			break
		}

		return e.complexity.AiExecution.OutputImageBase64(childComplexity), true

	case "AiExecution.outputText":
		if e.complexity.AiExecution.OutputText == nil {
			break
		}

		return e.complexity.AiExecution.OutputText(childComplexity), true

	case "AiExecution.outputTokens":
		if e.complexity.AiExecution.OutputTokens == nil {
			break
		}

		return e.complexity.AiExecution.OutputTokens(childComplexity), true

	case "AiExecution.outputkvs":
		if e.complexity.AiExecution.Outputkvs == nil {
			break
		}

		return e.complexity.AiExecution.Outputkvs(childComplexity), true

	case "AiExecution.prompt":
		if e.complexity.AiExecution.Prompt == nil {
			break
		}

		return e.complexity.AiExecution.Prompt(childComplexity), true

	case "AiExecution.runBy":
		if e.complexity.AiExecution.RunBy == nil {
			break
		}

		return e.complexity.AiExecution.RunBy(childComplexity), true

	case "AiExecution.runSajuProfileUid":
		if e.complexity.AiExecution.RunSajuProfileUID == nil {
			break
		}

		return e.complexity.AiExecution.RunSajuProfileUID(childComplexity), true

	case "AiExecution.size":
		if e.complexity.AiExecution.Size == nil {
			break
		}

		return e.complexity.AiExecution.Size(childComplexity), true

	case "AiExecution.status":
		if e.complexity.AiExecution.Status == nil {
			break
		}

		return e.complexity.AiExecution.Status(childComplexity), true

	case "AiExecution.temperature":
		if e.complexity.AiExecution.Temperature == nil {
			break
		}

		return e.complexity.AiExecution.Temperature(childComplexity), true

	case "AiExecution.totalTokens":
		if e.complexity.AiExecution.TotalTokens == nil {
			break
		}

		return e.complexity.AiExecution.TotalTokens(childComplexity), true

	case "AiExecution.uid":
		if e.complexity.AiExecution.UID == nil {
			break
		}

		return e.complexity.AiExecution.UID(childComplexity), true

	case "AiExecution.updatedAt":
		if e.complexity.AiExecution.UpdatedAt == nil {
			break
		}

		return e.complexity.AiExecution.UpdatedAt(childComplexity), true

	case "AiExecution.valued_prompt":
		if e.complexity.AiExecution.ValuedPrompt == nil {
			break
		}

		return e.complexity.AiExecution.ValuedPrompt(childComplexity), true

	case "AiMeta.createdAt":
		if e.complexity.AiMeta.CreatedAt == nil {
			break
		}

		return e.complexity.AiMeta.CreatedAt(childComplexity), true

	case "AiMeta.desc":
		if e.complexity.AiMeta.Desc == nil {
			break
		}

		return e.complexity.AiMeta.Desc(childComplexity), true

	case "AiMeta.id":
		if e.complexity.AiMeta.ID == nil {
			break
		}

		return e.complexity.AiMeta.ID(childComplexity), true

	case "AiMeta.inUse":
		if e.complexity.AiMeta.InUse == nil {
			break
		}

		return e.complexity.AiMeta.InUse(childComplexity), true

	case "AiMeta.maxTokens":
		if e.complexity.AiMeta.MaxTokens == nil {
			break
		}

		return e.complexity.AiMeta.MaxTokens(childComplexity), true

	case "AiMeta.metaType":
		if e.complexity.AiMeta.MetaType == nil {
			break
		}

		return e.complexity.AiMeta.MetaType(childComplexity), true

	case "AiMeta.model":
		if e.complexity.AiMeta.Model == nil {
			break
		}

		return e.complexity.AiMeta.Model(childComplexity), true

	case "AiMeta.name":
		if e.complexity.AiMeta.Name == nil {
			break
		}

		return e.complexity.AiMeta.Name(childComplexity), true

	case "AiMeta.prompt":
		if e.complexity.AiMeta.Prompt == nil {
			break
		}

		return e.complexity.AiMeta.Prompt(childComplexity), true

	case "AiMeta.size":
		if e.complexity.AiMeta.Size == nil {
			break
		}

		return e.complexity.AiMeta.Size(childComplexity), true

	case "AiMeta.temperature":
		if e.complexity.AiMeta.Temperature == nil {
			break
		}

		return e.complexity.AiMeta.Temperature(childComplexity), true

	case "AiMeta.uid":
		if e.complexity.AiMeta.UID == nil {
			break
		}

		return e.complexity.AiMeta.UID(childComplexity), true

	case "AiMeta.updatedAt":
		if e.complexity.AiMeta.UpdatedAt == nil {
			break
		}

		return e.complexity.AiMeta.UpdatedAt(childComplexity), true

	case "AiMetaType.hasInputImage":
		if e.complexity.AiMetaType.HasInputImage == nil {
			break
		}

		return e.complexity.AiMetaType.HasInputImage(childComplexity), true

	case "AiMetaType.hasOutputImage":
		if e.complexity.AiMetaType.HasOutputImage == nil {
			break
		}

		return e.complexity.AiMetaType.HasOutputImage(childComplexity), true

	case "AiMetaType.id":
		if e.complexity.AiMetaType.ID == nil {
			break
		}

		return e.complexity.AiMetaType.ID(childComplexity), true

	case "AiMetaType.inputFields":
		if e.complexity.AiMetaType.InputFields == nil {
			break
		}

		return e.complexity.AiMetaType.InputFields(childComplexity), true

	case "AiMetaType.outputFields":
		if e.complexity.AiMetaType.OutputFields == nil {
			break
		}

		return e.complexity.AiMetaType.OutputFields(childComplexity), true

	case "AiMetaType.type":
		if e.complexity.AiMetaType.Type == nil {
			break
		}

		return e.complexity.AiMetaType.Type(childComplexity), true

	case "KV.k":
		if e.complexity.KV.K == nil {
			break
		}

		return e.complexity.KV.K(childComplexity), true

	case "KV.v":
		if e.complexity.KV.V == nil {
			break
		}

		return e.complexity.KV.V(childComplexity), true

	case "Mutation.createPhyIdealPartner":
		if e.complexity.Mutation.CreatePhyIdealPartner == nil {
			break
		}

		args, err := ec.field_Mutation_createPhyIdealPartner_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreatePhyIdealPartner(childComplexity, args["input"].(model.PhyIdealPartnerCreateInput)), true

	case "Mutation.createSajuProfile":
		if e.complexity.Mutation.CreateSajuProfile == nil {
			break
		}

		args, err := ec.field_Mutation_createSajuProfile_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateSajuProfile(childComplexity, args["input"].(model.SajuProfileCreateInput)), true

	case "Mutation.delAiMeta":
		if e.complexity.Mutation.DelAiMeta == nil {
			break
		}

		args, err := ec.field_Mutation_delAiMeta_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DelAiMeta(childComplexity, args["uid"].(string)), true

	case "Mutation.deletePhyIdealPartner":
		if e.complexity.Mutation.DeletePhyIdealPartner == nil {
			break
		}

		args, err := ec.field_Mutation_deletePhyIdealPartner_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeletePhyIdealPartner(childComplexity, args["uid"].(string)), true

	case "Mutation.deleteSajuProfile":
		if e.complexity.Mutation.DeleteSajuProfile == nil {
			break
		}

		args, err := ec.field_Mutation_deleteSajuProfile_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeleteSajuProfile(childComplexity, args["uid"].(string)), true

	case "Mutation.putAiMeta":
		if e.complexity.Mutation.PutAiMeta == nil {
			break
		}

		args, err := ec.field_Mutation_putAiMeta_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.PutAiMeta(childComplexity, args["input"].(model.AiMetaInput)), true

	case "Mutation.runAiExecution":
		if e.complexity.Mutation.RunAiExecution == nil {
			break
		}

		args, err := ec.field_Mutation_runAiExecution_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.RunAiExecution(childComplexity, args["input"].(model.AiExcutionInput)), true

	case "Mutation.setAiMetaDefault":
		if e.complexity.Mutation.SetAiMetaDefault == nil {
			break
		}

		args, err := ec.field_Mutation_setAiMetaDefault_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.SetAiMetaDefault(childComplexity, args["uid"].(string)), true

	case "Mutation.setAiMetaInUse":
		if e.complexity.Mutation.SetAiMetaInUse == nil {
			break
		}

		args, err := ec.field_Mutation_setAiMetaInUse_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.SetAiMetaInUse(childComplexity, args["uid"].(string)), true

	case "PhyIdealPartner.age":
		if e.complexity.PhyIdealPartner.Age == nil {
			break
		}

		return e.complexity.PhyIdealPartner.Age(childComplexity), true

	case "PhyIdealPartner.createdAt":
		if e.complexity.PhyIdealPartner.CreatedAt == nil {
			break
		}

		return e.complexity.PhyIdealPartner.CreatedAt(childComplexity), true

	case "PhyIdealPartner.embeddingModel":
		if e.complexity.PhyIdealPartner.EmbeddingModel == nil {
			break
		}

		return e.complexity.PhyIdealPartner.EmbeddingModel(childComplexity), true

	case "PhyIdealPartner.embeddingText":
		if e.complexity.PhyIdealPartner.EmbeddingText == nil {
			break
		}

		return e.complexity.PhyIdealPartner.EmbeddingText(childComplexity), true

	case "PhyIdealPartner.featureEyes":
		if e.complexity.PhyIdealPartner.FeatureEyes == nil {
			break
		}

		return e.complexity.PhyIdealPartner.FeatureEyes(childComplexity), true

	case "PhyIdealPartner.featureFaceShape":
		if e.complexity.PhyIdealPartner.FeatureFaceShape == nil {
			break
		}

		return e.complexity.PhyIdealPartner.FeatureFaceShape(childComplexity), true

	case "PhyIdealPartner.featureMouth":
		if e.complexity.PhyIdealPartner.FeatureMouth == nil {
			break
		}

		return e.complexity.PhyIdealPartner.FeatureMouth(childComplexity), true

	case "PhyIdealPartner.featureNose":
		if e.complexity.PhyIdealPartner.FeatureNose == nil {
			break
		}

		return e.complexity.PhyIdealPartner.FeatureNose(childComplexity), true

	case "PhyIdealPartner.hasImage":
		if e.complexity.PhyIdealPartner.HasImage == nil {
			break
		}

		return e.complexity.PhyIdealPartner.HasImage(childComplexity), true

	case "PhyIdealPartner.id":
		if e.complexity.PhyIdealPartner.ID == nil {
			break
		}

		return e.complexity.PhyIdealPartner.ID(childComplexity), true

	case "PhyIdealPartner.image":
		if e.complexity.PhyIdealPartner.Image == nil {
			break
		}

		return e.complexity.PhyIdealPartner.Image(childComplexity), true

	case "PhyIdealPartner.personalityMatch":
		if e.complexity.PhyIdealPartner.PersonalityMatch == nil {
			break
		}

		return e.complexity.PhyIdealPartner.PersonalityMatch(childComplexity), true

	case "PhyIdealPartner.sex":
		if e.complexity.PhyIdealPartner.Sex == nil {
			break
		}

		return e.complexity.PhyIdealPartner.Sex(childComplexity), true

	case "PhyIdealPartner.similarityScore":
		if e.complexity.PhyIdealPartner.SimilarityScore == nil {
			break
		}

		return e.complexity.PhyIdealPartner.SimilarityScore(childComplexity), true

	case "PhyIdealPartner.summary":
		if e.complexity.PhyIdealPartner.Summary == nil {
			break
		}

		return e.complexity.PhyIdealPartner.Summary(childComplexity), true

	case "PhyIdealPartner.uid":
		if e.complexity.PhyIdealPartner.UID == nil {
			break
		}

		return e.complexity.PhyIdealPartner.UID(childComplexity), true

	case "PhyIdealPartner.updatedAt":
		if e.complexity.PhyIdealPartner.UpdatedAt == nil {
			break
		}

		return e.complexity.PhyIdealPartner.UpdatedAt(childComplexity), true

	case "Query.aiExecution":
		if e.complexity.Query.AiExecution == nil {
			break
		}

		args, err := ec.field_Query_aiExecution_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.AiExecution(childComplexity, args["uid"].(string)), true

	case "Query.aiExecutions":
		if e.complexity.Query.AiExecutions == nil {
			break
		}

		args, err := ec.field_Query_aiExecutions_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.AiExecutions(childComplexity, args["input"].(model.AiExecutionSearchInput)), true

	case "Query.aiMeta":
		if e.complexity.Query.AiMeta == nil {
			break
		}

		args, err := ec.field_Query_aiMeta_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.AiMeta(childComplexity, args["uid"].(string)), true

	case "Query.aiMetaKVs":
		if e.complexity.Query.AiMetaKVs == nil {
			break
		}

		args, err := ec.field_Query_aiMetaKVs_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.AiMetaKVs(childComplexity, args["input"].(model.AiMetaKVsInput)), true

	case "Query.aiMetaTypes":
		if e.complexity.Query.AiMetaTypes == nil {
			break
		}

		return e.complexity.Query.AiMetaTypes(childComplexity), true

	case "Query.aiMetas":
		if e.complexity.Query.AiMetas == nil {
			break
		}

		args, err := ec.field_Query_aiMetas_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.AiMetas(childComplexity, args["input"].(model.AiMetaSearchInput)), true

	case "Query.palja":
		if e.complexity.Query.Palja == nil {
			break
		}

		args, err := ec.field_Query_palja_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.Palja(childComplexity, args["birthdate"].(string), args["timezone"].(string)), true

	case "Query.phyIdealPartner":
		if e.complexity.Query.PhyIdealPartner == nil {
			break
		}

		args, err := ec.field_Query_phyIdealPartner_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.PhyIdealPartner(childComplexity, args["uid"].(string)), true

	case "Query.phyIdealPartners":
		if e.complexity.Query.PhyIdealPartners == nil {
			break
		}

		args, err := ec.field_Query_phyIdealPartners_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.PhyIdealPartners(childComplexity, args["input"].(model.PhyIdealPartnerSearchInput)), true

	case "Query.sajuProfile":
		if e.complexity.Query.SajuProfile == nil {
			break
		}

		args, err := ec.field_Query_sajuProfile_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.SajuProfile(childComplexity, args["uid"].(string)), true

	case "Query.sajuProfileLogs":
		if e.complexity.Query.SajuProfileLogs == nil {
			break
		}

		args, err := ec.field_Query_sajuProfileLogs_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.SajuProfileLogs(childComplexity, args["input"].(model.SajuProfileLogSearchInput)), true

	case "Query.sajuProfileSimilarPartners":
		if e.complexity.Query.SajuProfileSimilarPartners == nil {
			break
		}

		args, err := ec.field_Query_sajuProfileSimilarPartners_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.SajuProfileSimilarPartners(childComplexity, args["uid"].(string), args["limit"].(int), args["offset"].(int)), true

	case "Query.sajuProfiles":
		if e.complexity.Query.SajuProfiles == nil {
			break
		}

		args, err := ec.field_Query_sajuProfiles_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.SajuProfiles(childComplexity, args["input"].(model.SajuProfileSearchInput)), true

	case "SajuProfile.birthdate":
		if e.complexity.SajuProfile.Birthdate == nil {
			break
		}

		return e.complexity.SajuProfile.Birthdate(childComplexity), true

	case "SajuProfile.createdAt":
		if e.complexity.SajuProfile.CreatedAt == nil {
			break
		}

		return e.complexity.SajuProfile.CreatedAt(childComplexity), true

	case "SajuProfile.email":
		if e.complexity.SajuProfile.Email == nil {
			break
		}

		return e.complexity.SajuProfile.Email(childComplexity), true

	case "SajuProfile.id":
		if e.complexity.SajuProfile.ID == nil {
			break
		}

		return e.complexity.SajuProfile.ID(childComplexity), true

	case "SajuProfile.image":
		if e.complexity.SajuProfile.Image == nil {
			break
		}

		return e.complexity.SajuProfile.Image(childComplexity), true

	case "SajuProfile.imageMimeType":
		if e.complexity.SajuProfile.ImageMimeType == nil {
			break
		}

		return e.complexity.SajuProfile.ImageMimeType(childComplexity), true

	case "SajuProfile.myFeatureEyes":
		if e.complexity.SajuProfile.MyFeatureEyes == nil {
			break
		}

		return e.complexity.SajuProfile.MyFeatureEyes(childComplexity), true

	case "SajuProfile.myFeatureFaceShape":
		if e.complexity.SajuProfile.MyFeatureFaceShape == nil {
			break
		}

		return e.complexity.SajuProfile.MyFeatureFaceShape(childComplexity), true

	case "SajuProfile.myFeatureMouth":
		if e.complexity.SajuProfile.MyFeatureMouth == nil {
			break
		}

		return e.complexity.SajuProfile.MyFeatureMouth(childComplexity), true

	case "SajuProfile.myFeatureNose":
		if e.complexity.SajuProfile.MyFeatureNose == nil {
			break
		}

		return e.complexity.SajuProfile.MyFeatureNose(childComplexity), true

	case "SajuProfile.myFeatureNotes":
		if e.complexity.SajuProfile.MyFeatureNotes == nil {
			break
		}

		return e.complexity.SajuProfile.MyFeatureNotes(childComplexity), true

	case "SajuProfile.nickname":
		if e.complexity.SajuProfile.Nickname == nil {
			break
		}

		return e.complexity.SajuProfile.Nickname(childComplexity), true

	case "SajuProfile.palja":
		if e.complexity.SajuProfile.Palja == nil {
			break
		}

		return e.complexity.SajuProfile.Palja(childComplexity), true

	case "SajuProfile.partnerAge":
		if e.complexity.SajuProfile.PartnerAge == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerAge(childComplexity), true

	case "SajuProfile.partnerEmbeddingText":
		if e.complexity.SajuProfile.PartnerEmbeddingText == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerEmbeddingText(childComplexity), true

	case "SajuProfile.partnerFeatureEyes":
		if e.complexity.SajuProfile.PartnerFeatureEyes == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerFeatureEyes(childComplexity), true

	case "SajuProfile.partnerFeatureFaceShape":
		if e.complexity.SajuProfile.PartnerFeatureFaceShape == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerFeatureFaceShape(childComplexity), true

	case "SajuProfile.partnerFeatureMouth":
		if e.complexity.SajuProfile.PartnerFeatureMouth == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerFeatureMouth(childComplexity), true

	case "SajuProfile.partnerFeatureNose":
		if e.complexity.SajuProfile.PartnerFeatureNose == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerFeatureNose(childComplexity), true

	case "SajuProfile.partnerMatchTips":
		if e.complexity.SajuProfile.PartnerMatchTips == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerMatchTips(childComplexity), true

	case "SajuProfile.partnerPersonalityMatch":
		if e.complexity.SajuProfile.PartnerPersonalityMatch == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerPersonalityMatch(childComplexity), true

	case "SajuProfile.partnerSex":
		if e.complexity.SajuProfile.PartnerSex == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerSex(childComplexity), true

	case "SajuProfile.partnerSummary":
		if e.complexity.SajuProfile.PartnerSummary == nil {
			break
		}

		return e.complexity.SajuProfile.PartnerSummary(childComplexity), true

	case "SajuProfile.phyContent":
		if e.complexity.SajuProfile.PhyContent == nil {
			break
		}

		return e.complexity.SajuProfile.PhyContent(childComplexity), true

	case "SajuProfile.phyPartnerSimilarity":
		if e.complexity.SajuProfile.PhyPartnerSimilarity == nil {
			break
		}

		return e.complexity.SajuProfile.PhyPartnerSimilarity(childComplexity), true

	case "SajuProfile.phyPartnerUid":
		if e.complexity.SajuProfile.PhyPartnerUID == nil {
			break
		}

		return e.complexity.SajuProfile.PhyPartnerUID(childComplexity), true

	case "SajuProfile.phySummary":
		if e.complexity.SajuProfile.PhySummary == nil {
			break
		}

		return e.complexity.SajuProfile.PhySummary(childComplexity), true

	case "SajuProfile.sajuContent":
		if e.complexity.SajuProfile.SajuContent == nil {
			break
		}

		return e.complexity.SajuProfile.SajuContent(childComplexity), true

	case "SajuProfile.sajuSummary":
		if e.complexity.SajuProfile.SajuSummary == nil {
			break
		}

		return e.complexity.SajuProfile.SajuSummary(childComplexity), true

	case "SajuProfile.sex":
		if e.complexity.SajuProfile.Sex == nil {
			break
		}

		return e.complexity.SajuProfile.Sex(childComplexity), true

	case "SajuProfile.uid":
		if e.complexity.SajuProfile.UID == nil {
			break
		}

		return e.complexity.SajuProfile.UID(childComplexity), true

	case "SajuProfile.updatedAt":
		if e.complexity.SajuProfile.UpdatedAt == nil {
			break
		}

		return e.complexity.SajuProfile.UpdatedAt(childComplexity), true

	case "SajuProfileLog.createdAt":
		if e.complexity.SajuProfileLog.CreatedAt == nil {
			break
		}

		return e.complexity.SajuProfileLog.CreatedAt(childComplexity), true

	case "SajuProfileLog.id":
		if e.complexity.SajuProfileLog.ID == nil {
			break
		}

		return e.complexity.SajuProfileLog.ID(childComplexity), true

	case "SajuProfileLog.sajuUid":
		if e.complexity.SajuProfileLog.SajuUID == nil {
			break
		}

		return e.complexity.SajuProfileLog.SajuUID(childComplexity), true

	case "SajuProfileLog.status":
		if e.complexity.SajuProfileLog.Status == nil {
			break
		}

		return e.complexity.SajuProfileLog.Status(childComplexity), true

	case "SajuProfileLog.text":
		if e.complexity.SajuProfileLog.Text == nil {
			break
		}

		return e.complexity.SajuProfileLog.Text(childComplexity), true

	case "SajuProfileLog.uid":
		if e.complexity.SajuProfileLog.UID == nil {
			break
		}

		return e.complexity.SajuProfileLog.UID(childComplexity), true

	case "SajuProfileLog.updatedAt":
		if e.complexity.SajuProfileLog.UpdatedAt == nil {
			break
		}

		return e.complexity.SajuProfileLog.UpdatedAt(childComplexity), true

	case "SimpleResult.base64Value":
		if e.complexity.SimpleResult.Base64Value == nil {
			break
		}

		return e.complexity.SimpleResult.Base64Value(childComplexity), true

	case "SimpleResult.err":
		if e.complexity.SimpleResult.Err == nil {
			break
		}

		return e.complexity.SimpleResult.Err(childComplexity), true

	case "SimpleResult.kvs":
		if e.complexity.SimpleResult.Kvs == nil {
			break
		}

		return e.complexity.SimpleResult.Kvs(childComplexity), true

	case "SimpleResult.limit":
		if e.complexity.SimpleResult.Limit == nil {
			break
		}

		return e.complexity.SimpleResult.Limit(childComplexity), true

	case "SimpleResult.msg":
		if e.complexity.SimpleResult.Msg == nil {
			break
		}

		return e.complexity.SimpleResult.Msg(childComplexity), true

	case "SimpleResult.node":
		if e.complexity.SimpleResult.Node == nil {
			break
		}

		return e.complexity.SimpleResult.Node(childComplexity), true

	case "SimpleResult.nodes":
		if e.complexity.SimpleResult.Nodes == nil {
			break
		}

		return e.complexity.SimpleResult.Nodes(childComplexity), true

	case "SimpleResult.offset":
		if e.complexity.SimpleResult.Offset == nil {
			break
		}

		return e.complexity.SimpleResult.Offset(childComplexity), true

	case "SimpleResult.ok":
		if e.complexity.SimpleResult.Ok == nil {
			break
		}

		return e.complexity.SimpleResult.Ok(childComplexity), true

	case "SimpleResult.total":
		if e.complexity.SimpleResult.Total == nil {
			break
		}

		return e.complexity.SimpleResult.Total(childComplexity), true

	case "SimpleResult.uid":
		if e.complexity.SimpleResult.UID == nil {
			break
		}

		return e.complexity.SimpleResult.UID(childComplexity), true

	case "SimpleResult.value":
		if e.complexity.SimpleResult.Value == nil {
			break
		}

		return e.complexity.SimpleResult.Value(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputAiExcutionInput,
		ec.unmarshalInputAiExecutionSearchInput,
		ec.unmarshalInputAiMetaInput,
		ec.unmarshalInputAiMetaKVsInput,
		ec.unmarshalInputAiMetaSearchInput,
		ec.unmarshalInputKVInput,
		ec.unmarshalInputPhyIdealPartnerCreateInput,
		ec.unmarshalInputPhyIdealPartnerSearchInput,
		ec.unmarshalInputSajuProfileCreateInput,
		ec.unmarshalInputSajuProfileLogSearchInput,
		ec.unmarshalInputSajuProfileSearchInput,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

var sources = []*ast.Source{
	{Name: "../admgql.graphql", Input: `scalar BigInt

interface Node {
  id: ID
}
type KV {
  k: String!
  v: String!
}
input KVInput {
  k: String!
  v: String!
}

type SimpleResult {
  ok: Boolean!
  uid: String
  err: String
  msg: String
  value: String
  base64Value: String
  node: Node
  nodes: [Node!]
  kvs: [KV!]
  total: Int
  limit: Int
  offset: Int
}

type Query {
  sajuProfiles(input: SajuProfileSearchInput!): SimpleResult!
  sajuProfile(uid: String!): SimpleResult!
  sajuProfileSimilarPartners(
    uid: String!
    limit: Int!
    offset: Int!
  ): SimpleResult!
  phyIdealPartners(input: PhyIdealPartnerSearchInput!): SimpleResult!
  phyIdealPartner(uid: String!): SimpleResult!
  sajuProfileLogs(input: SajuProfileLogSearchInput!): SimpleResult!

  aiMetas(input: AiMetaSearchInput!): SimpleResult!
  aiMeta(uid: String!): SimpleResult!
  aiMetaTypes: SimpleResult!
  aiMetaKVs(input:AiMetaKVsInput!): SimpleResult! #kvs는 출력되는값
  aiExecutions(input: AiExecutionSearchInput!): SimpleResult!
  aiExecution(uid: String!): SimpleResult!
  palja(birthdate: String!, timezone: String!): SimpleResult!
}

type Mutation {
  createSajuProfile(input: SajuProfileCreateInput!): SimpleResult
  deleteSajuProfile(uid: String!): SimpleResult

  createPhyIdealPartner(input: PhyIdealPartnerCreateInput!): SimpleResult
  deletePhyIdealPartner(uid: String!): SimpleResult

  putAiMeta(input: AiMetaInput!): SimpleResult # AI Meta 생성 및 수정
  setAiMetaInUse(uid: String!): SimpleResult # AI Meta 사용 여부 설정
  delAiMeta(uid: String!): SimpleResult # AI Meta 삭제
  setAiMetaDefault(uid: String!): SimpleResult # AI Meta 기본 설정
  runAiExecution(input: AiExcutionInput!): SimpleResult!
}

type SajuProfile implements Node {
  id: ID
  uid: String!
  createdAt: BigInt!
  updatedAt: BigInt!
  sex: String!
  birthdate: String!
  palja: String!
  email: String!
  image: String! # base64 encoded image
  imageMimeType: String!
  nickname: String!
  #
  sajuSummary: String!
  sajuContent: String!
  #
  phySummary: String!
  phyContent: String!
  #
  myFeatureEyes: String!
  myFeatureNose: String!
  myFeatureMouth: String!
  myFeatureFaceShape: String!
  myFeatureNotes: String!
  #
  partnerEmbeddingText: String!
  partnerMatchTips: String!
  #
  partnerSummary: String!
  partnerFeatureEyes: String!
  partnerFeatureNose: String!
  partnerFeatureMouth: String!
  partnerFeatureFaceShape: String!
  partnerPersonalityMatch: String!
  partnerSex: String!
  partnerAge: Int!

  #
  phyPartnerUid: String!
  phyPartnerSimilarity: Float!
}

input SajuProfileSearchInput {
  limit: Int!
  offset: Int!
  orderBy: String
  orderDirection: String
}

input SajuProfileCreateInput {
  image: String! # base64 encoded image
  birthdate: String! # yyyymmddhhmm format (hhmm optional)
  sex: String!
}

# phy ideal partner
type PhyIdealPartner implements Node {
  id: ID
  uid: String!
  createdAt: BigInt!
  updatedAt: BigInt!
  # input
  summary: String!
  featureEyes: String!
  featureNose: String!
  featureMouth: String!
  featureFaceShape: String!
  personalityMatch: String!
  sex: String!
  age: Int!
  # Image Data (Generated or Uploaded)
  image: String!
  # Embedding
  embeddingModel: String!
  embeddingText: String!

  # 유사도
  similarityScore: Float!
  hasImage: Boolean!
}

input PhyIdealPartnerCreateInput {
  summary: String!
  featureEyes: String!
  featureNose: String!
  featureMouth: String!
  featureFaceShape: String!
  personalityMatch: String!
  sex: String!
  age: Int!
  image: String # base64 encoded image (optional)
}

input PhyIdealPartnerSearchInput {
  limit: Int!
  offset: Int!
  sex: String
  hasImage: Boolean
}

# Saju Profile Log
type SajuProfileLog implements Node {
  id: ID
  uid: String!
  createdAt: BigInt!
  updatedAt: BigInt!
  sajuUid: String!
  status: String!
  text: String!
}
input SajuProfileLogSearchInput {
  limit: Int!
  offset: Int!
  sajuUid: String!
  status: String
}

# ai meta
type AiMeta implements Node {
  id: ID
  uid: String!
  createdAt: BigInt!
  updatedAt: BigInt!
  metaType: String!

  name: String!
  desc: String!
  prompt: String!
  model: String!
  temperature: Float!
  maxTokens: Int!
  size: String! # 1024x1024, 2048x2048, 4096x4096 // 이미지 사이즈

  inUse: Boolean! # 사용 중인지 여부 (true: 사용 중, false: 사용 중이지 않음)
}

input AiMetaInput {
  uid: String # optional
  name: String!
  desc: String!
  prompt: String!
  metaType: String # Saju, FaceFeature, Phy, IdealPartnerImage
  model: String!
  temperature: Float!
  maxTokens: Int!
  size: String! # 1024x1024, 2048x2048, 4096x4096 // 이미지 사이즈 
}

input AiMetaSearchInput {
  limit: Int!
  offset: Int!
  metaType: String # Saju, FaceFeature, Phy, IdealPartnerImage
  inUse: Boolean # 사용 중인지 여부 (true: 사용 중, false: 사용 중이지 않음)
}

# AI Excution
type AiExecution implements Node {
  id: ID
  uid: String!
  createdAt: BigInt!
  updatedAt: BigInt!
  metaUid: String!
  metaType: String!
  status: String!
  errorMessage: String!
  # real Request
  prompt: String!
  valued_prompt: String!
  inputkvs: [KV!]!
  outputkvs: [KV!]!
  model: String!
  temperature: Float!
  maxTokens: Int!
  size: String!
  inputImageBase64: String
  # result
  elapsedTime: Int!
  outputText: String
  outputImageBase64: String # if exists return base64 encoded image
  # usage
  inputTokens: Int!
  outputTokens: Int!
  totalTokens: Int!
  # 
  runBy: String # admin, system
  runSajuProfileUid: String # saju profile uid
}

input AiExcutionInput {
  metaUid: String!
  metaType: String!
  promptType: String! # text, vision, image
  prompt: String! # 프롬프트
  valued_prompt: String! # params가 적용된 프롬프트
  inputkvs: [KVInput!]! # 입력값들
  outputkvs: [KVInput!]! # 출력값들
  model: String!
  temperature: Float!
  maxTokens: Int!
  size: String!

  inputImageBase64: String
}

input AiExecutionSearchInput {
  limit: Int!
  offset: Int!
  metaType: String
  metaUid: String
  runBy: String # admin, system
  runSajuProfileUid: String # saju profile uid
}

# 
input AiMetaKVsInput {
  type: String! # Meta type 
  kvs: [KVInput!]! # 메타에 따른 입력값들 - 사전정의됨
}

type AiMetaType implements Node {
  id: ID!
  type: String!
  inputFields: [String!]!
  outputFields: [String!]!
  hasInputImage: Boolean!
  hasOutputImage: Boolean!
}`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
