// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() *string
}

type AiExcutionInput struct {
	MetaUID          string     `json:"metaUid"`
	MetaType         string     `json:"metaType"`
	PromptType       string     `json:"promptType"`
	Prompt           string     `json:"prompt"`
	ValuedPrompt     string     `json:"valued_prompt"`
	Inputkvs         []*KVInput `json:"inputkvs"`
	Outputkvs        []*KVInput `json:"outputkvs"`
	Model            string     `json:"model"`
	Temperature      float64    `json:"temperature"`
	MaxTokens        int        `json:"maxTokens"`
	Size             string     `json:"size"`
	InputImageBase64 *string    `json:"inputImageBase64,omitempty"`
}

type AiExecution struct {
	ID                *string `json:"id,omitempty"`
	UID               string  `json:"uid"`
	CreatedAt         int64   `json:"createdAt"`
	UpdatedAt         int64   `json:"updatedAt"`
	MetaUID           string  `json:"metaUid"`
	MetaType          string  `json:"metaType"`
	Status            string  `json:"status"`
	ErrorMessage      string  `json:"errorMessage"`
	Prompt            string  `json:"prompt"`
	ValuedPrompt      string  `json:"valued_prompt"`
	Inputkvs          []*Kv   `json:"inputkvs"`
	Outputkvs         []*Kv   `json:"outputkvs"`
	Model             string  `json:"model"`
	Temperature       float64 `json:"temperature"`
	MaxTokens         int     `json:"maxTokens"`
	Size              string  `json:"size"`
	InputImageBase64  *string `json:"inputImageBase64,omitempty"`
	ElapsedTime       int     `json:"elapsedTime"`
	OutputText        *string `json:"outputText,omitempty"`
	OutputImageBase64 *string `json:"outputImageBase64,omitempty"`
	InputTokens       int     `json:"inputTokens"`
	OutputTokens      int     `json:"outputTokens"`
	TotalTokens       int     `json:"totalTokens"`
	RunBy             *string `json:"runBy,omitempty"`
	RunSajuProfileUID *string `json:"runSajuProfileUid,omitempty"`
}

func (AiExecution) IsNode()             {}
func (this AiExecution) GetID() *string { return this.ID }

type AiExecutionSearchInput struct {
	Limit             int     `json:"limit"`
	Offset            int     `json:"offset"`
	MetaType          *string `json:"metaType,omitempty"`
	MetaUID           *string `json:"metaUid,omitempty"`
	RunBy             *string `json:"runBy,omitempty"`
	RunSajuProfileUID *string `json:"runSajuProfileUid,omitempty"`
}

type AiMeta struct {
	ID          *string `json:"id,omitempty"`
	UID         string  `json:"uid"`
	CreatedAt   int64   `json:"createdAt"`
	UpdatedAt   int64   `json:"updatedAt"`
	MetaType    string  `json:"metaType"`
	Name        string  `json:"name"`
	Desc        string  `json:"desc"`
	Prompt      string  `json:"prompt"`
	Model       string  `json:"model"`
	Temperature float64 `json:"temperature"`
	MaxTokens   int     `json:"maxTokens"`
	Size        string  `json:"size"`
	InUse       bool    `json:"inUse"`
}

func (AiMeta) IsNode()             {}
func (this AiMeta) GetID() *string { return this.ID }

type AiMetaInput struct {
	UID         *string `json:"uid,omitempty"`
	Name        string  `json:"name"`
	Desc        string  `json:"desc"`
	Prompt      string  `json:"prompt"`
	MetaType    *string `json:"metaType,omitempty"`
	Model       string  `json:"model"`
	Temperature float64 `json:"temperature"`
	MaxTokens   int     `json:"maxTokens"`
	Size        string  `json:"size"`
}

type AiMetaKVsInput struct {
	Type string     `json:"type"`
	Kvs  []*KVInput `json:"kvs"`
}

type AiMetaSearchInput struct {
	Limit    int     `json:"limit"`
	Offset   int     `json:"offset"`
	MetaType *string `json:"metaType,omitempty"`
	InUse    *bool   `json:"inUse,omitempty"`
}

type AiMetaType struct {
	ID             string   `json:"id"`
	Type           string   `json:"type"`
	InputFields    []string `json:"inputFields"`
	OutputFields   []string `json:"outputFields"`
	HasInputImage  bool     `json:"hasInputImage"`
	HasOutputImage bool     `json:"hasOutputImage"`
}

func (AiMetaType) IsNode()             {}
func (this AiMetaType) GetID() *string { return &this.ID }

type Kv struct {
	K string `json:"k"`
	V string `json:"v"`
}

type KVInput struct {
	K string `json:"k"`
	V string `json:"v"`
}

type Mutation struct {
}

type PhyIdealPartner struct {
	ID               *string `json:"id,omitempty"`
	UID              string  `json:"uid"`
	CreatedAt        int64   `json:"createdAt"`
	UpdatedAt        int64   `json:"updatedAt"`
	Summary          string  `json:"summary"`
	FeatureEyes      string  `json:"featureEyes"`
	FeatureNose      string  `json:"featureNose"`
	FeatureMouth     string  `json:"featureMouth"`
	FeatureFaceShape string  `json:"featureFaceShape"`
	PersonalityMatch string  `json:"personalityMatch"`
	Sex              string  `json:"sex"`
	Age              int     `json:"age"`
	Image            string  `json:"image"`
	EmbeddingModel   string  `json:"embeddingModel"`
	EmbeddingText    string  `json:"embeddingText"`
	SimilarityScore  float64 `json:"similarityScore"`
	HasImage         bool    `json:"hasImage"`
}

func (PhyIdealPartner) IsNode()             {}
func (this PhyIdealPartner) GetID() *string { return this.ID }

type PhyIdealPartnerCreateInput struct {
	Summary          string  `json:"summary"`
	FeatureEyes      string  `json:"featureEyes"`
	FeatureNose      string  `json:"featureNose"`
	FeatureMouth     string  `json:"featureMouth"`
	FeatureFaceShape string  `json:"featureFaceShape"`
	PersonalityMatch string  `json:"personalityMatch"`
	Sex              string  `json:"sex"`
	Age              int     `json:"age"`
	Image            *string `json:"image,omitempty"`
}

type PhyIdealPartnerSearchInput struct {
	Limit    int     `json:"limit"`
	Offset   int     `json:"offset"`
	Sex      *string `json:"sex,omitempty"`
	HasImage *bool   `json:"hasImage,omitempty"`
}

type Query struct {
}

type SajuProfile struct {
	ID                      *string `json:"id,omitempty"`
	UID                     string  `json:"uid"`
	CreatedAt               int64   `json:"createdAt"`
	UpdatedAt               int64   `json:"updatedAt"`
	Sex                     string  `json:"sex"`
	Birthdate               string  `json:"birthdate"`
	Palja                   string  `json:"palja"`
	Email                   string  `json:"email"`
	Image                   string  `json:"image"`
	ImageMimeType           string  `json:"imageMimeType"`
	Nickname                string  `json:"nickname"`
	SajuSummary             string  `json:"sajuSummary"`
	SajuContent             string  `json:"sajuContent"`
	PhySummary              string  `json:"phySummary"`
	PhyContent              string  `json:"phyContent"`
	MyFeatureEyes           string  `json:"myFeatureEyes"`
	MyFeatureNose           string  `json:"myFeatureNose"`
	MyFeatureMouth          string  `json:"myFeatureMouth"`
	MyFeatureFaceShape      string  `json:"myFeatureFaceShape"`
	MyFeatureNotes          string  `json:"myFeatureNotes"`
	PartnerEmbeddingText    string  `json:"partnerEmbeddingText"`
	PartnerMatchTips        string  `json:"partnerMatchTips"`
	PartnerSummary          string  `json:"partnerSummary"`
	PartnerFeatureEyes      string  `json:"partnerFeatureEyes"`
	PartnerFeatureNose      string  `json:"partnerFeatureNose"`
	PartnerFeatureMouth     string  `json:"partnerFeatureMouth"`
	PartnerFeatureFaceShape string  `json:"partnerFeatureFaceShape"`
	PartnerPersonalityMatch string  `json:"partnerPersonalityMatch"`
	PartnerSex              string  `json:"partnerSex"`
	PartnerAge              int     `json:"partnerAge"`
	PhyPartnerUID           string  `json:"phyPartnerUid"`
	PhyPartnerSimilarity    float64 `json:"phyPartnerSimilarity"`
}

func (SajuProfile) IsNode()             {}
func (this SajuProfile) GetID() *string { return this.ID }

type SajuProfileCreateInput struct {
	Image     string `json:"image"`
	Birthdate string `json:"birthdate"`
	Sex       string `json:"sex"`
}

type SajuProfileLog struct {
	ID        *string `json:"id,omitempty"`
	UID       string  `json:"uid"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
	SajuUID   string  `json:"sajuUid"`
	Status    string  `json:"status"`
	Text      string  `json:"text"`
}

func (SajuProfileLog) IsNode()             {}
func (this SajuProfileLog) GetID() *string { return this.ID }

type SajuProfileLogSearchInput struct {
	Limit   int     `json:"limit"`
	Offset  int     `json:"offset"`
	SajuUID string  `json:"sajuUid"`
	Status  *string `json:"status,omitempty"`
}

type SajuProfileSearchInput struct {
	Limit          int     `json:"limit"`
	Offset         int     `json:"offset"`
	OrderBy        *string `json:"orderBy,omitempty"`
	OrderDirection *string `json:"orderDirection,omitempty"`
}

type SimpleResult struct {
	Ok          bool    `json:"ok"`
	UID         *string `json:"uid,omitempty"`
	Err         *string `json:"err,omitempty"`
	Msg         *string `json:"msg,omitempty"`
	Value       *string `json:"value,omitempty"`
	Base64Value *string `json:"base64Value,omitempty"`
	Node        Node    `json:"node,omitempty"`
	Nodes       []Node  `json:"nodes,omitempty"`
	Kvs         []*Kv   `json:"kvs,omitempty"`
	Total       *int    `json:"total,omitempty"`
	Limit       *int    `json:"limit,omitempty"`
	Offset      *int    `json:"offset,omitempty"`
}
