// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type AiExcutionInput struct {
	MetaUID     string   `json:"metaUid"`
	MetaType    string   `json:"metaType"`
	Prompt      string   `json:"prompt"`
	Params      []string `json:"params"`
	Model       string   `json:"model"`
	Temperature float64  `json:"temperature"`
	MaxTokens   int      `json:"maxTokens"`
	Size        string   `json:"size"`
}

type AiExecution struct {
	ID          string   `json:"id"`
	UID         string   `json:"uid"`
	CreatedAt   int64    `json:"createdAt"`
	UpdatedAt   int64    `json:"updatedAt"`
	MetaUID     string   `json:"metaUid"`
	MetaType    string   `json:"metaType"`
	Status      string   `json:"status"`
	Prompt      string   `json:"prompt"`
	Params      []string `json:"params"`
	Model       string   `json:"model"`
	Temperature float64  `json:"temperature"`
	MaxTokens   int      `json:"maxTokens"`
	Size        string   `json:"size"`
	OutputText  *string  `json:"outputText,omitempty"`
	OutputImage *string  `json:"outputImage,omitempty"`
}

func (AiExecution) IsNode()            {}
func (this AiExecution) GetID() string { return this.ID }

type AiExecutionSearchInput struct {
	Limit    int     `json:"limit"`
	Offset   int     `json:"offset"`
	MetaType *string `json:"metaType,omitempty"`
	MetaUID  *string `json:"metaUid,omitempty"`
}

type AiMeta struct {
	ID        string `json:"id"`
	UID       string `json:"uid"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
	MetaType  string `json:"metaType"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	Prompt    string `json:"prompt"`
}

func (AiMeta) IsNode()            {}
func (this AiMeta) GetID() string { return this.ID }

type AiMetaInput struct {
	UID      *string `json:"uid,omitempty"`
	Name     string  `json:"name"`
	Desc     string  `json:"desc"`
	Prompt   string  `json:"prompt"`
	MetaType *string `json:"metaType,omitempty"`
}

type AiMetaSearchInput struct {
	Limit    int     `json:"limit"`
	Offset   int     `json:"offset"`
	MetaType *string `json:"metaType,omitempty"`
}

type Mutation struct {
}

type PhyIdealPartner struct {
	ID               string  `json:"id"`
	UID              string  `json:"uid"`
	CreatedAt        int64   `json:"createdAt"`
	UpdatedAt        int64   `json:"updatedAt"`
	Summary          string  `json:"summary"`
	FeatureEyes      string  `json:"featureEyes"`
	FeatureNose      string  `json:"featureNose"`
	FeatureMouth     string  `json:"featureMouth"`
	FeatureFaceShape string  `json:"featureFaceShape"`
	PersonalityMatch string  `json:"personalityMatch"`
	Sex              string  `json:"sex"`
	Age              int     `json:"age"`
	Image            string  `json:"image"`
	SimilarityScore  float64 `json:"similarityScore"`
}

func (PhyIdealPartner) IsNode()            {}
func (this PhyIdealPartner) GetID() string { return this.ID }

type PhyIdealPartnerCreateInput struct {
	Summary          string  `json:"summary"`
	FeatureEyes      string  `json:"featureEyes"`
	FeatureNose      string  `json:"featureNose"`
	FeatureMouth     string  `json:"featureMouth"`
	FeatureFaceShape string  `json:"featureFaceShape"`
	PersonalityMatch string  `json:"personalityMatch"`
	Sex              string  `json:"sex"`
	Age              int     `json:"age"`
	Image            *string `json:"image,omitempty"`
}

type PhyIdealPartnerSearchInput struct {
	Limit  int     `json:"limit"`
	Offset int     `json:"offset"`
	Sex    *string `json:"sex,omitempty"`
}

type Query struct {
}

type SajuProfile struct {
	ID                      string  `json:"id"`
	UID                     string  `json:"uid"`
	CreatedAt               int64   `json:"createdAt"`
	UpdatedAt               int64   `json:"updatedAt"`
	Sex                     string  `json:"sex"`
	Birthdate               string  `json:"birthdate"`
	Palja                   string  `json:"palja"`
	Email                   string  `json:"email"`
	Image                   string  `json:"image"`
	ImageMimeType           string  `json:"imageMimeType"`
	Nickname                string  `json:"nickname"`
	SajuSummary             string  `json:"sajuSummary"`
	SajuContent             string  `json:"sajuContent"`
	PhySummary              string  `json:"phySummary"`
	PhyContent              string  `json:"phyContent"`
	MyFeatureEyes           string  `json:"myFeatureEyes"`
	MyFeatureNose           string  `json:"myFeatureNose"`
	MyFeatureMouth          string  `json:"myFeatureMouth"`
	MyFeatureFaceShape      string  `json:"myFeatureFaceShape"`
	MyFeatureNotes          string  `json:"myFeatureNotes"`
	PartnerMatchTips        string  `json:"partnerMatchTips"`
	PartnerSummary          string  `json:"partnerSummary"`
	PartnerFeatureEyes      string  `json:"partnerFeatureEyes"`
	PartnerFeatureNose      string  `json:"partnerFeatureNose"`
	PartnerFeatureMouth     string  `json:"partnerFeatureMouth"`
	PartnerFeatureFaceShape string  `json:"partnerFeatureFaceShape"`
	PartnerPersonalityMatch string  `json:"partnerPersonalityMatch"`
	PartnerSex              string  `json:"partnerSex"`
	PartnerAge              int     `json:"partnerAge"`
	PhyPartnerUID           string  `json:"phyPartnerUid"`
	PhyPartnerSimilarity    float64 `json:"phyPartnerSimilarity"`
}

func (SajuProfile) IsNode()            {}
func (this SajuProfile) GetID() string { return this.ID }

type SajuProfileCreateInput struct {
	Image     string `json:"image"`
	Birthdate string `json:"birthdate"`
	Sex       string `json:"sex"`
}

type SajuProfileSearchInput struct {
	Limit          int     `json:"limit"`
	Offset         int     `json:"offset"`
	OrderBy        *string `json:"orderBy,omitempty"`
	OrderDirection *string `json:"orderDirection,omitempty"`
}

type SimpleResult struct {
	Ok     bool    `json:"ok"`
	UID    *string `json:"uid,omitempty"`
	Msg    *string `json:"msg,omitempty"`
	Value  *string `json:"value,omitempty"`
	Node   Node    `json:"node,omitempty"`
	Nodes  []Node  `json:"nodes,omitempty"`
	Total  *int    `json:"total,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
}
